name: Issue Creation Tracker
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Issue Details
        run: |
          echo "Issue creator: ${{ github.event.issue.user.login }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue url: ${{ github.event.issue.html_url }}"
      - name: Google Chat Notification
        run: |
            curl --location --request POST '${{ secrets.WEBHOOK }}' \
            --header 'Content-Type: application/json; charset=UTF-8' \
            --data-raw '{
              New Issue: "Issue No: #${{ github.event.issue.number }}" \
              Title: ${{ github.event.issue.title }} \
              Submitted by: ${{ github.event.issue.user.login }} \
              URL:  ${{ github.event.issue.html_url }}

             }'
